# Site settings
title: Michael Brennan
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio and project showcase for Michael Brennan
baseurl: ""
url: "https://michaelwbrennan.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .gitignore
  - README.md